# This workflow will apply a label to an issue when it is closed.
# For more information, see:
# https://github.com/christianvuerings/add-labels

name: Add Label
on:
  issues:
    types: 
      - closed

jobs:
  add-label:
    name: Add Label
    runs-on: ubuntu-latest
    steps:
      - uses: KeisukeYamashita/attach-labels@v1
        if: ${{ contains(github.event.issue.title, 'Bug') || contains(github.event.comment.body, 'BUG') || contains(github.event.comment.body, 'bug') }}
        with:
          labels: unvalidated
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
