# This workflow will apply a label to an issue when it is closed.
# For more information, see:
# https://github.com/christianvuerings/add-labels

name: Add Label
on:
  issues:
    types: [closed]

jobs:
  add-label:
    name: Add Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hianhianhian/add-labels@v1.1.1
        with:
          labels: unvalidated
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
