name: Add or Remove Validation Label

on: [issue_comment]

jobs:
  remove_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-remove-labels@v1.3.0
        if: ${{ contains(github.event.comment.body, 'Validated') || contains(github.event.comment.body, 'validated') }}
        with:
          labels: unvalidated
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  add_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@2ce5d41b4b6aa8503e285553f75ed56e0a40bae0
        if: ${{ contains(github.event.comment.body, 'Validated') || contains(github.event.comment.body, 'validated') }}
        with:
          labels: validated
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
